name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release --wasm

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Use GitHub Secret for Vercel Token
          vercel-org-id: team_Pc8KJn2iSBhbBT26HYBqMFDx
          vercel-project-id: prj_DAhptLP488yHRJ9RVeiStE8h0smZ
          working-directory: ./build/web
          vercel-args: '--prod'
